name                  = "yellow-waterfall-020a"
main                  = "worker.js"
compatibility_date    = "2024-09-23"

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "HISTORY_STORE"
id      = "a937413d81d24ccab6cc95dbe922a42c"
